# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenWeatherDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenWeatherDemo
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.12.5'
  pod 'MBProgressHUD', '~> 1.2.0'

end
